# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

platform :ios do
  before_all do
    #ENV['TEAM_ID'] = "" #replace me when not in public
    setup_circle_ci
  end

  desc "Run Tests"
  lane :test do |options|
    scheme = options[:scheme] || ENV["SCHEME"]
    logPath = options[:logPath] || './build'
    # Run Tests against given scheme
    scan(
      scheme: scheme,
      buildlog_path: logPath,
      code_coverage: true
    )

  end

  #desc "Ad-hoc build"
  #lane :adhoc do
  #  match(type: "adhoc")
  #  gym(export_method: "ad-hoc")
  #end

  desc "Build and Package IPA"
  lane :build do |options|
    projectName = options[:projectName] || ENV["PROJECT_NAME"]
    xcodeproj = options[:xcodeproj] || "#{projectName}.xcodeproj"
    scheme = options[:scheme] || ENV["SCHEME"]
    buildPath = options[:buildPath] || './build'
    logPath = options[:logPath] || './build'

    # Ensure the project team is PGE
    update_project_team(path: xcodeproj)

    # Set the version and build numbers
      
    old_version = get_version_number
    new_version = "#{old_version}.#{ENV['BUILD_NUMBER']}"
    increment_version_number(version_number: "#{new_version}")
    increment_build_number(build_number: "#{ENV["BUILD_NUMBER"]}")

    # Build and package the IPA against the given scheme.
    # Sets the output name of the IPA and the build directory and export type
    gym(
      scheme: scheme,
      output_name: "#{projectName}-#{new_version}.ipa",
      clean: true,
      output_directory: buildPath,
      buildlog_path: logPath,
      export_method: "ad-hoc"
    )
  end
end
end
